ENVIRONMENT: local
PORT: 3000
LOG_LEVEL: info
SERVICE_NAME: devices-api
JWT_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
BLOCKCHAIN_NODE_URL: http://127.0.0.1:8545
DEX_GRPC_ADDRESS: localhost:5557
USERS_API_GRPC_ADDRESS: localhost:8089
CONTRACT_ADDRESS_WHITELIST: 0x90c4d6113ec88dd4bdf12f26db2b3998fd13a144