replicaCount: 1
image:
  repository: dimozone/token-exchange-api
  pullPolicy: IfNotPresent
  tag: 7f82320
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
cronJob:
  enabled: false
  schedule: 0 0 * * 0
env:
  PORT: 8888
  ENVIRONMENT: dev
  LOG_LEVEL: info
  JWT_KEY_SET_URL: vauth.dev.dimo.zone/keys
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
ingress:
  enabled: false
resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics:
    - name: topic.device.status.enriched
      config:
        segment.ms: '3600000'
        compression.type: producer
        cleanup.policy: compact,delete
        min.compaction.lag.ms: '3600000'
    - name: table.device.definition
      config:
        segment.ms: '3600000'
        compression.type: producer
        cleanup.policy: compact
        min.compaction.lag.ms: '3600000'
        min.cleanable.dirty.ratio: '0.01'
        delete.retention.ms: '3600000'
    - name: table.device.definition.metadata
      config:
        segment.ms: '3600000'
        compression.type: producer
        cleanup.policy: compact
        min.compaction.lag.ms: '3600000'
        min.cleanable.dirty.ratio: '0.01'
        delete.retention.ms: '3600000'
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
