// Code generated by MockGen. DO NOT EDIT.
// Source: ../services/dex_service.go
//
// Generated by this command:
//
//	mockgen -source ../services/dex_service.go -destination ./dex_service_mock_test.go -package controllers
//

// Package controllers is a generated GoMock package.
package controllers
