// Code generated by MockGen. DO NOT EDIT.
// Source: ../middleware/valid_dev_license.go
//
// Generated by this command:
//
//	mockgen -source ../middleware/valid_dev_license.go -destination ./identity_service_mock_test.go -package controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityService is a mock of IdentityService interface.
type MockIdentityService struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceMockRecorder
	isgomock struct{}
}

// MockIdentityServiceMockRecorder is the mock recorder for MockIdentityService.
type MockIdentityServiceMockRecorder struct {
	mock *MockIdentityService
}

// NewMockIdentityService creates a new mock instance.
func NewMockIdentityService(ctrl *gomock.Controller) *MockIdentityService {
	mock := &MockIdentityService{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityService) EXPECT() *MockIdentityServiceMockRecorder {
	return m.recorder
}

// IsDevLicense mocks base method.
func (m *MockIdentityService) IsDevLicense(ctx context.Context, ethAddr common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDevLicense", ctx, ethAddr)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDevLicense indicates an expected call of IsDevLicense.
func (mr *MockIdentityServiceMockRecorder) IsDevLicense(ctx, ethAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDevLicense", reflect.TypeOf((*MockIdentityService)(nil).IsDevLicense), ctx, ethAddr)
}
