apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "token-exchange-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/ethereum/rpc_url
    secretKey: BLOCKCHAIN_NODE_URL
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: token-exchange-api-dev-secret
    template:
      metadata: {}
