apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "device-definition-join-processor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/metatx/ethereum/rpc_url
      name: BLOCKCHAIN_NODE_URL