apiVersion: v1
kind: Service
metadata:
  name: {{ include "device-definition-join-processor.fullname" . }}
  labels:
    {{- include "device-definition-join-processor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "device-definition-join-processor.selectorLabels" . | nindent 4 }}
