// Code generated by MockGen. DO NOT EDIT.
// Source: ./template.go
//
// Generated by this command:
//
//	mockgen -source ./template.go -destination ./template_mock_test.go -package template
//

// Package template is a generated GoMock package.
package template

import (
	context "context"
	json "encoding/json"
	big "math/big"
	reflect "reflect"

	cloudevent "github.com/DIMO-Network/cloudevent"
	template "github.com/DIMO-Network/token-exchange-api/internal/contracts/template"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplate is a mock of Template interface.
type MockTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateMockRecorder
	isgomock struct{}
}

// MockTemplateMockRecorder is the mock recorder for MockTemplate.
type MockTemplateMockRecorder struct {
	mock *MockTemplate
}

// NewMockTemplate creates a new mock instance.
func NewMockTemplate(ctrl *gomock.Controller) *MockTemplate {
	mock := &MockTemplate{ctrl: ctrl}
	mock.recorder = &MockTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplate) EXPECT() *MockTemplateMockRecorder {
	return m.recorder
}

// IsTemplateActive mocks base method.
func (m *MockTemplate) IsTemplateActive(opts *bind.CallOpts, templateID *big.Int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTemplateActive", opts, templateID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTemplateActive indicates an expected call of IsTemplateActive.
func (mr *MockTemplateMockRecorder) IsTemplateActive(opts, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTemplateActive", reflect.TypeOf((*MockTemplate)(nil).IsTemplateActive), opts, templateID)
}

// Templates mocks base method.
func (m *MockTemplate) Templates(opts *bind.CallOpts, templateID *big.Int) (template.ITemplateTemplateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Templates", opts, templateID)
	ret0, _ := ret[0].(template.ITemplateTemplateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Templates indicates an expected call of Templates.
func (mr *MockTemplateMockRecorder) Templates(opts, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Templates", reflect.TypeOf((*MockTemplate)(nil).Templates), opts, templateID)
}

// MockIPFSClient is a mock of IPFSClient interface.
type MockIPFSClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPFSClientMockRecorder
	isgomock struct{}
}

// MockIPFSClientMockRecorder is the mock recorder for MockIPFSClient.
type MockIPFSClientMockRecorder struct {
	mock *MockIPFSClient
}

// NewMockIPFSClient creates a new mock instance.
func NewMockIPFSClient(ctrl *gomock.Controller) *MockIPFSClient {
	mock := &MockIPFSClient{ctrl: ctrl}
	mock.recorder = &MockIPFSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPFSClient) EXPECT() *MockIPFSClientMockRecorder {
	return m.recorder
}

// GetValidSacdDoc mocks base method.
func (m *MockIPFSClient) GetValidSacdDoc(ctx context.Context, source string) (*cloudevent.RawEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidSacdDoc", ctx, source)
	ret0, _ := ret[0].(*cloudevent.RawEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidSacdDoc indicates an expected call of GetValidSacdDoc.
func (mr *MockIPFSClientMockRecorder) GetValidSacdDoc(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidSacdDoc", reflect.TypeOf((*MockIPFSClient)(nil).GetValidSacdDoc), ctx, source)
}

// MockSignatureValidator is a mock of SignatureValidator interface.
type MockSignatureValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureValidatorMockRecorder
	isgomock struct{}
}

// MockSignatureValidatorMockRecorder is the mock recorder for MockSignatureValidator.
type MockSignatureValidatorMockRecorder struct {
	mock *MockSignatureValidator
}

// NewMockSignatureValidator creates a new mock instance.
func NewMockSignatureValidator(ctrl *gomock.Controller) *MockSignatureValidator {
	mock := &MockSignatureValidator{ctrl: ctrl}
	mock.recorder = &MockSignatureValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignatureValidator) EXPECT() *MockSignatureValidatorMockRecorder {
	return m.recorder
}

// ValidateSignature mocks base method.
func (m *MockSignatureValidator) ValidateSignature(ctx context.Context, payload json.RawMessage, signature string, ethAddr common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSignature", ctx, payload, signature, ethAddr)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSignature indicates an expected call of ValidateSignature.
func (mr *MockSignatureValidatorMockRecorder) ValidateSignature(ctx, payload, signature, ethAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSignature", reflect.TypeOf((*MockSignatureValidator)(nil).ValidateSignature), ctx, payload, signature, ethAddr)
}
