// Code generated by MockGen. DO NOT EDIT.
// Source: ./rpc.go
//
// Generated by this command:
//
//	mockgen -source ./rpc.go -destination ./rpc_mock_test.go -package rpc_test
//

// Package rpc_test is a generated GoMock package.
package rpc_test

import (
	context "context"
	reflect "reflect"

	signercheck "github.com/DIMO-Network/token-exchange-api/pkg/signercheck"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockSignerChecker is a mock of SignerChecker interface.
type MockSignerChecker struct {
	ctrl     *gomock.Controller
	recorder *MockSignerCheckerMockRecorder
	isgomock struct{}
}

// MockSignerCheckerMockRecorder is the mock recorder for MockSignerChecker.
type MockSignerCheckerMockRecorder struct {
	mock *MockSignerChecker
}

// NewMockSignerChecker creates a new mock instance.
func NewMockSignerChecker(ctrl *gomock.Controller) *MockSignerChecker {
	mock := &MockSignerChecker{ctrl: ctrl}
	mock.recorder = &MockSignerCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignerChecker) EXPECT() *MockSignerCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockSignerChecker) Check(ctx context.Context, license, signer common.Address) (signercheck.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, license, signer)
	ret0, _ := ret[0].(signercheck.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockSignerCheckerMockRecorder) Check(ctx, license, signer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockSignerChecker)(nil).Check), ctx, license, signer)
}
