// Code generated by MockGen. DO NOT EDIT.
// Source: ./access.go
//
// Generated by this command:
//
//	mockgen -source ./access.go -destination ./access_mock_test.go -package access
//

// Package access is a generated GoMock package.
package access

import (
	context "context"
	json "encoding/json"
	big "math/big"
	reflect "reflect"

	sacd "github.com/DIMO-Network/token-exchange-api/internal/contracts/sacd"
	template "github.com/DIMO-Network/token-exchange-api/internal/contracts/template"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockSACDInterface is a mock of SACDInterface interface.
type MockSACDInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSACDInterfaceMockRecorder
	isgomock struct{}
}

// MockSACDInterfaceMockRecorder is the mock recorder for MockSACDInterface.
type MockSACDInterfaceMockRecorder struct {
	mock *MockSACDInterface
}

// NewMockSACDInterface creates a new mock instance.
func NewMockSACDInterface(ctrl *gomock.Controller) *MockSACDInterface {
	mock := &MockSACDInterface{ctrl: ctrl}
	mock.recorder = &MockSACDInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSACDInterface) EXPECT() *MockSACDInterfaceMockRecorder {
	return m.recorder
}

// CurrentPermissionRecord mocks base method.
func (m *MockSACDInterface) CurrentPermissionRecord(opts *bind.CallOpts, asset common.Address, tokenID *big.Int, grantee common.Address) (sacd.ISacdPermissionRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentPermissionRecord", opts, asset, tokenID, grantee)
	ret0, _ := ret[0].(sacd.ISacdPermissionRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentPermissionRecord indicates an expected call of CurrentPermissionRecord.
func (mr *MockSACDInterfaceMockRecorder) CurrentPermissionRecord(opts, asset, tokenID, grantee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentPermissionRecord", reflect.TypeOf((*MockSACDInterface)(nil).CurrentPermissionRecord), opts, asset, tokenID, grantee)
}

// GetPermissions mocks base method.
func (m *MockSACDInterface) GetPermissions(opts *bind.CallOpts, asset common.Address, tokenID *big.Int, grantee common.Address, permissions *big.Int) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", opts, asset, tokenID, grantee, permissions)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockSACDInterfaceMockRecorder) GetPermissions(opts, asset, tokenID, grantee, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockSACDInterface)(nil).GetPermissions), opts, asset, tokenID, grantee, permissions)
}

// MockTemplateInterface is a mock of TemplateInterface interface.
type MockTemplateInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateInterfaceMockRecorder
	isgomock struct{}
}

// MockTemplateInterfaceMockRecorder is the mock recorder for MockTemplateInterface.
type MockTemplateInterfaceMockRecorder struct {
	mock *MockTemplateInterface
}

// NewMockTemplateInterface creates a new mock instance.
func NewMockTemplateInterface(ctrl *gomock.Controller) *MockTemplateInterface {
	mock := &MockTemplateInterface{ctrl: ctrl}
	mock.recorder = &MockTemplateInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateInterface) EXPECT() *MockTemplateInterfaceMockRecorder {
	return m.recorder
}

// Templates mocks base method.
func (m *MockTemplateInterface) Templates(opts *bind.CallOpts, templateID *big.Int) (template.ITemplateTemplateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Templates", opts, templateID)
	ret0, _ := ret[0].(template.ITemplateTemplateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Templates indicates an expected call of Templates.
func (mr *MockTemplateInterfaceMockRecorder) Templates(opts, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Templates", reflect.TypeOf((*MockTemplateInterface)(nil).Templates), opts, templateID)
}

// MockErc1271Interface is a mock of Erc1271Interface interface.
type MockErc1271Interface struct {
	ctrl     *gomock.Controller
	recorder *MockErc1271InterfaceMockRecorder
	isgomock struct{}
}

// MockErc1271InterfaceMockRecorder is the mock recorder for MockErc1271Interface.
type MockErc1271InterfaceMockRecorder struct {
	mock *MockErc1271Interface
}

// NewMockErc1271Interface creates a new mock instance.
func NewMockErc1271Interface(ctrl *gomock.Controller) *MockErc1271Interface {
	mock := &MockErc1271Interface{ctrl: ctrl}
	mock.recorder = &MockErc1271InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErc1271Interface) EXPECT() *MockErc1271InterfaceMockRecorder {
	return m.recorder
}

// IsValidSignature mocks base method.
func (m *MockErc1271Interface) IsValidSignature(opts *bind.CallOpts, hash [32]byte, signature []byte) ([4]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidSignature", opts, hash, signature)
	ret0, _ := ret[0].([4]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidSignature indicates an expected call of IsValidSignature.
func (mr *MockErc1271InterfaceMockRecorder) IsValidSignature(opts, hash, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidSignature", reflect.TypeOf((*MockErc1271Interface)(nil).IsValidSignature), opts, hash, signature)
}

// MockIPFSClient is a mock of IPFSClient interface.
type MockIPFSClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPFSClientMockRecorder
	isgomock struct{}
}

// MockIPFSClientMockRecorder is the mock recorder for MockIPFSClient.
type MockIPFSClientMockRecorder struct {
	mock *MockIPFSClient
}

// NewMockIPFSClient creates a new mock instance.
func NewMockIPFSClient(ctrl *gomock.Controller) *MockIPFSClient {
	mock := &MockIPFSClient{ctrl: ctrl}
	mock.recorder = &MockIPFSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPFSClient) EXPECT() *MockIPFSClientMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockIPFSClient) Fetch(ctx context.Context, cid string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, cid)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockIPFSClientMockRecorder) Fetch(ctx, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockIPFSClient)(nil).Fetch), ctx, cid)
}

// MockSignatureValidator is a mock of SignatureValidator interface.
type MockSignatureValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureValidatorMockRecorder
	isgomock struct{}
}

// MockSignatureValidatorMockRecorder is the mock recorder for MockSignatureValidator.
type MockSignatureValidatorMockRecorder struct {
	mock *MockSignatureValidator
}

// NewMockSignatureValidator creates a new mock instance.
func NewMockSignatureValidator(ctrl *gomock.Controller) *MockSignatureValidator {
	mock := &MockSignatureValidator{ctrl: ctrl}
	mock.recorder = &MockSignatureValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignatureValidator) EXPECT() *MockSignatureValidatorMockRecorder {
	return m.recorder
}

// ValidateSignature mocks base method.
func (m *MockSignatureValidator) ValidateSignature(ctx context.Context, payload json.RawMessage, signature string, ethAddr common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSignature", ctx, payload, signature, ethAddr)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSignature indicates an expected call of ValidateSignature.
func (mr *MockSignatureValidatorMockRecorder) ValidateSignature(ctx, payload, signature, ethAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSignature", reflect.TypeOf((*MockSignatureValidator)(nil).ValidateSignature), ctx, payload, signature, ethAddr)
}
