// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: pkg/grpc/token-exchange-api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenExchangeService_AccessCheck_FullMethodName = "/grpc.TokenExchangeService/AccessCheck"
)

// TokenExchangeServiceClient is the client API for TokenExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenExchangeServiceClient interface {
	AccessCheck(ctx context.Context, in *AccessCheckRequest, opts ...grpc.CallOption) (*AccessCheckResponse, error)
}

type tokenExchangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenExchangeServiceClient(cc grpc.ClientConnInterface) TokenExchangeServiceClient {
	return &tokenExchangeServiceClient{cc}
}

func (c *tokenExchangeServiceClient) AccessCheck(ctx context.Context, in *AccessCheckRequest, opts ...grpc.CallOption) (*AccessCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessCheckResponse)
	err := c.cc.Invoke(ctx, TokenExchangeService_AccessCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenExchangeServiceServer is the server API for TokenExchangeService service.
// All implementations must embed UnimplementedTokenExchangeServiceServer
// for forward compatibility.
type TokenExchangeServiceServer interface {
	AccessCheck(context.Context, *AccessCheckRequest) (*AccessCheckResponse, error)
	mustEmbedUnimplementedTokenExchangeServiceServer()
}

// UnimplementedTokenExchangeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenExchangeServiceServer struct{}

func (UnimplementedTokenExchangeServiceServer) AccessCheck(context.Context, *AccessCheckRequest) (*AccessCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessCheck not implemented")
}
func (UnimplementedTokenExchangeServiceServer) mustEmbedUnimplementedTokenExchangeServiceServer() {}
func (UnimplementedTokenExchangeServiceServer) testEmbeddedByValue()                              {}

// UnsafeTokenExchangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenExchangeServiceServer will
// result in compilation errors.
type UnsafeTokenExchangeServiceServer interface {
	mustEmbedUnimplementedTokenExchangeServiceServer()
}

func RegisterTokenExchangeServiceServer(s grpc.ServiceRegistrar, srv TokenExchangeServiceServer) {
	// If the following call pancis, it indicates UnimplementedTokenExchangeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenExchangeService_ServiceDesc, srv)
}

func _TokenExchangeService_AccessCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenExchangeServiceServer).AccessCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenExchangeService_AccessCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenExchangeServiceServer).AccessCheck(ctx, req.(*AccessCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenExchangeService_ServiceDesc is the grpc.ServiceDesc for TokenExchangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenExchangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TokenExchangeService",
	HandlerType: (*TokenExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccessCheck",
			Handler:    _TokenExchangeService_AccessCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/token-exchange-api.proto",
}
