// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pkg/grpc/token-exchange-api.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The grantee address.
	Grantee string `protobuf:"bytes,1,opt,name=grantee,proto3" json:"grantee,omitempty"`
	// The token Id of the VC to check.
	Asset string `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// The permissions to check.
	Privileges []string `protobuf:"bytes,3,rep,name=privileges,proto3" json:"privileges,omitempty"`
	// The events to check.
	Events        []*EventFilter `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessCheckRequest) Reset() {
	*x = AccessCheckRequest{}
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckRequest) ProtoMessage() {}

func (x *AccessCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckRequest.ProtoReflect.Descriptor instead.
func (*AccessCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_token_exchange_api_proto_rawDescGZIP(), []int{0}
}

func (x *AccessCheckRequest) GetGrantee() string {
	if x != nil {
		return x.Grantee
	}
	return ""
}

func (x *AccessCheckRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *AccessCheckRequest) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *AccessCheckRequest) GetEvents() []*EventFilter {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_token_exchange_api_proto_rawDescGZIP(), []int{1}
}

func (x *EventFilter) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventFilter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventFilter) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AccessCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	RichError     *RichError             `protobuf:"bytes,2,opt,name=rich_error,json=richError,proto3" json:"rich_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessCheckResponse) Reset() {
	*x = AccessCheckResponse{}
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckResponse) ProtoMessage() {}

func (x *AccessCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckResponse.ProtoReflect.Descriptor instead.
func (*AccessCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_token_exchange_api_proto_rawDescGZIP(), []int{2}
}

func (x *AccessCheckResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *AccessCheckResponse) GetRichError() *RichError {
	if x != nil {
		return x.RichError
	}
	return nil
}

type RichError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ExternalMsg   string                 `protobuf:"bytes,2,opt,name=external_msg,json=externalMsg,proto3" json:"external_msg,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichError) Reset() {
	*x = RichError{}
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichError) ProtoMessage() {}

func (x *RichError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_token_exchange_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichError.ProtoReflect.Descriptor instead.
func (*RichError) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_token_exchange_api_proto_rawDescGZIP(), []int{3}
}

func (x *RichError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RichError) GetExternalMsg() string {
	if x != nil {
		return x.ExternalMsg
	}
	return ""
}

func (x *RichError) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_pkg_grpc_token_exchange_api_proto protoreflect.FileDescriptor

const file_pkg_grpc_token_exchange_api_proto_rawDesc = "" +
	"\n" +
	"!pkg/grpc/token-exchange-api.proto\x12\x04grpc\"\x8f\x01\n" +
	"\x12AccessCheckRequest\x12\x18\n" +
	"\agrantee\x18\x01 \x01(\tR\agrantee\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x1e\n" +
	"\n" +
	"privileges\x18\x03 \x03(\tR\n" +
	"privileges\x12)\n" +
	"\x06events\x18\x04 \x03(\v2\x11.grpc.EventFilterR\x06events\"V\n" +
	"\vEventFilter\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"d\n" +
	"\x13AccessCheckResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12.\n" +
	"\n" +
	"rich_error\x18\x02 \x01(\v2\x0f.grpc.RichErrorR\trichError\"T\n" +
	"\tRichError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12!\n" +
	"\fexternal_msg\x18\x02 \x01(\tR\vexternalMsg\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err2Z\n" +
	"\x14TokenExchangeService\x12B\n" +
	"\vAccessCheck\x12\x18.grpc.AccessCheckRequest\x1a\x19.grpc.AccessCheckResponseB5Z3github.com/DIMO-Network/token-exchange-api/pkg/grpcb\x06proto3"

var (
	file_pkg_grpc_token_exchange_api_proto_rawDescOnce sync.Once
	file_pkg_grpc_token_exchange_api_proto_rawDescData []byte
)

func file_pkg_grpc_token_exchange_api_proto_rawDescGZIP() []byte {
	file_pkg_grpc_token_exchange_api_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_token_exchange_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_token_exchange_api_proto_rawDesc), len(file_pkg_grpc_token_exchange_api_proto_rawDesc)))
	})
	return file_pkg_grpc_token_exchange_api_proto_rawDescData
}

var file_pkg_grpc_token_exchange_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_grpc_token_exchange_api_proto_goTypes = []any{
	(*AccessCheckRequest)(nil),  // 0: grpc.AccessCheckRequest
	(*EventFilter)(nil),         // 1: grpc.EventFilter
	(*AccessCheckResponse)(nil), // 2: grpc.AccessCheckResponse
	(*RichError)(nil),           // 3: grpc.RichError
}
var file_pkg_grpc_token_exchange_api_proto_depIdxs = []int32{
	1, // 0: grpc.AccessCheckRequest.events:type_name -> grpc.EventFilter
	3, // 1: grpc.AccessCheckResponse.rich_error:type_name -> grpc.RichError
	0, // 2: grpc.TokenExchangeService.AccessCheck:input_type -> grpc.AccessCheckRequest
	2, // 3: grpc.TokenExchangeService.AccessCheck:output_type -> grpc.AccessCheckResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_grpc_token_exchange_api_proto_init() }
func file_pkg_grpc_token_exchange_api_proto_init() {
	if File_pkg_grpc_token_exchange_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_token_exchange_api_proto_rawDesc), len(file_pkg_grpc_token_exchange_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_token_exchange_api_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_token_exchange_api_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_token_exchange_api_proto_msgTypes,
	}.Build()
	File_pkg_grpc_token_exchange_api_proto = out.File
	file_pkg_grpc_token_exchange_api_proto_goTypes = nil
	file_pkg_grpc_token_exchange_api_proto_depIdxs = nil
}
