basePath: /v1
definitions:
  big.Int:
    type: object
  github_com_DIMO-Network_token-exchange-api_internal_controllers.PermissionTokenRequest:
    type: object
  github_com_DIMO-Network_token-exchange-api_internal_controllers.PermissionTokenResponse:
    properties:
      token:
        type: string
    type: object
  internal_controllers.PermissionTokenRequest:
    type: object
  internal_controllers.PermissionTokenResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  title: DIMO Token Exchange API
  version: "1.0"
paths:
  /tokens/exchange:
    post:
      consumes:
      - application/json
      description: Returns a signed token with the requested privileges.
      parameters:
      - description: 'Requested privileges: must include address, token id, and privilege
          ids'
        in: body
        name: tokenRequest
        required: true
        schema:
          $ref: '#/definitions/internal_controllers.PermissionTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers.PermissionTokenResponse'
      security:
      - BearerAuth: []
      summary: privileges on the correct token.
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
