basePath: /v1
definitions:
  internal_controllers.CloudEvents:
    properties:
      events:
        items:
          $ref: '#/definitions/internal_controllers.EventFilter'
        type: array
    type: object
  internal_controllers.EventFilter:
    properties:
      eventType:
        type: string
      ids:
        items:
          type: string
        type: array
      source:
        type: string
    type: object
  internal_controllers.TokenRequest:
    properties:
      audience:
        description: Audience is the intended audience for the token.
        items:
          type: string
        type: array
      chainId:
        description: |-
          ChainID is the chain ID of the NFT contract.
          If not provided, the chain ID for the DIMO registry will be used.
        type: integer
      cloudEvents:
        allOf:
        - $ref: '#/definitions/internal_controllers.CloudEvents'
        description: CloudEvent request, includes attestations
      nftContractAddress:
        description: |-
          NFTContractAddress is the address of the NFT contract. Privileges will be checked
          on-chain at this address. Address must be in the 0x format e.g. 0x5FbDB2315678afecb367f032d93F642f64180aa3.
          Varying case is okay.
        example: 0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF
        type: string
      privileges:
        description: Privileges is a list of the desired privileges. It must not be
          empty.
        example:
        - 1
        - 2
        - 3
        - 4
        items:
          type: integer
        type: array
      tokenId:
        description: TokenID is the NFT token id.
        example: 7
        type: integer
    required:
    - nftContractAddress
    - privileges
    - tokenId
    type: object
  internal_controllers.TokenResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  title: DIMO Token Exchange API
  version: "1.0"
paths:
  /tokens/exchange:
    post:
      consumes:
      - application/json
      description: Returns a signed token with the requested privileges.
      parameters:
      - description: 'Requested privileges: must include address, token id, and privilege
          ids'
        in: body
        name: tokenRequest
        required: true
        schema:
          $ref: '#/definitions/internal_controllers.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers.TokenResponse'
      security:
      - BearerAuth: []
      summary: privileges on the correct token.
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
