name: gotest

on:
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -v -json ./... > test.json -timeout 360s

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.7.0
        with:
          test-results: test.json
